### PR TITLE
Create cross-platform Conda environment file

### PR DESCRIPTION
**Pull request by guikarist**
This environment file is very convenient for Conda users to create an Pommerman environment by `conda env create -f env.yml`.

And Conda is much better because it can manage versions of Python and installation of CUDA toolkits.

This file is tested on Windows and Linux. And versions inside are consistent with those in `requirements.txt`.

### CODE REVIEW

**Comment by beyretb** [comment]
Thanks a lot for this, we'll have a look at it a little later and run some tests to confirm we can merge this.

**Comment by guikarist** [comment]
Not at all. For consistency, you can change the `name: animal-ai` to `name: animalai`.

**Comment by guikarist** [comment]
Is it ready to be merged?

**Comment by guikarist** [comment]
Now `README.md` has also been updated.

**Pull request merged**
